# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "zram" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/70fe3706-ec7d-4df8-bff9-5b0e209318a5";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" "noatime" "datacow" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/70fe3706-ec7d-4df8-bff9-5b0e209318a5";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" "noatime" "datacow" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/70fe3706-ec7d-4df8-bff9-5b0e209318a5";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" "noatime" "datacow" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/70fe3706-ec7d-4df8-bff9-5b0e209318a5";
      fsType = "btrfs";
      options = [ "subvol=persist" "compress=zstd" "noatime" "datacow" ];
      neededForBoot = true;
    };

  fileSystems."/persist/lxd" =
    { device = "/dev/disk/by-uuid/70fe3706-ec7d-4df8-bff9-5b0e209318a5";
      fsType = "btrfs";
      options = [ "subvol=persist" "compress=zstd" "noatime" "datacow" ];
      # neededForBoot = true;
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/70fe3706-ec7d-4df8-bff9-5b0e209318a5";
      fsType = "btrfs";
      options = [ "subvol=log" "compress=zstd" "noatime" "datacow" ];
      neededForBoot = true;
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5C35-E43E";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp31s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp36s0f3u1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp36s0f3u2.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
